/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteGiftArgs } from "./DeleteGiftArgs";
import { GiftFindManyArgs } from "./GiftFindManyArgs";
import { GiftFindUniqueArgs } from "./GiftFindUniqueArgs";
import { Gift } from "./Gift";
import { GiftService } from "../gift.service";

@graphql.Resolver(() => Gift)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class GiftResolverBase {
  constructor(
    protected readonly service: GiftService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "read",
    possession: "any",
  })
  async _giftsMeta(
    @graphql.Args() args: GiftFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Gift])
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "read",
    possession: "any",
  })
  async gifts(@graphql.Args() args: GiftFindManyArgs): Promise<Gift[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Gift, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "read",
    possession: "own",
  })
  async gift(@graphql.Args() args: GiftFindUniqueArgs): Promise<Gift | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Gift)
  @nestAccessControl.UseRoles({
    resource: "Gift",
    action: "delete",
    possession: "any",
  })
  async deleteGift(@graphql.Args() args: DeleteGiftArgs): Promise<Gift | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
