/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSpeakerArgs } from "./CreateSpeakerArgs";
import { UpdateSpeakerArgs } from "./UpdateSpeakerArgs";
import { DeleteSpeakerArgs } from "./DeleteSpeakerArgs";
import { SpeakerFindManyArgs } from "./SpeakerFindManyArgs";
import { SpeakerFindUniqueArgs } from "./SpeakerFindUniqueArgs";
import { Speaker } from "./Speaker";
import { SpeakerService } from "../speaker.service";

@graphql.Resolver(() => Speaker)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SpeakerResolverBase {
  constructor(
    protected readonly service: SpeakerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Speaker",
    action: "read",
    possession: "any",
  })
  async _speakersMeta(
    @graphql.Args() args: SpeakerFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Speaker])
  @nestAccessControl.UseRoles({
    resource: "Speaker",
    action: "read",
    possession: "any",
  })
  async speakers(
    @graphql.Args() args: SpeakerFindManyArgs
  ): Promise<Speaker[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Speaker, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Speaker",
    action: "read",
    possession: "own",
  })
  async speaker(
    @graphql.Args() args: SpeakerFindUniqueArgs
  ): Promise<Speaker | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Speaker)
  @nestAccessControl.UseRoles({
    resource: "Speaker",
    action: "create",
    possession: "any",
  })
  async createSpeaker(
    @graphql.Args() args: CreateSpeakerArgs
  ): Promise<Speaker> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Speaker)
  @nestAccessControl.UseRoles({
    resource: "Speaker",
    action: "update",
    possession: "any",
  })
  async updateSpeaker(
    @graphql.Args() args: UpdateSpeakerArgs
  ): Promise<Speaker | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Speaker)
  @nestAccessControl.UseRoles({
    resource: "Speaker",
    action: "delete",
    possession: "any",
  })
  async deleteSpeaker(
    @graphql.Args() args: DeleteSpeakerArgs
  ): Promise<Speaker | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
